### ISSUE TITLE
enquire link interval

### ISSUE THREAD

**Issue by c-castillo** [podshumok/python-smpplib#10]
Hi,

I've been trying to connect to a server who needs certain enquire link interval, is this configurable on the library? (or I need to do a wrapper)

**Comment by podshumok** [comment]
Hello, `enquire_link` is sent after `socket.timeout`.
You can try set timeout with https://docs.python.org/2/library/socket.html#socket.socket.settimeout
If it doesn't work, you should probably patch `Client`

**Comment by eigenein** [comment]
Well, actually, `Client` accepts `timeout` parameter which is then passed to socket. So it's already in place.

**Comment by eigenein** [comment]
I'm closing the issue. Please re-open it if the question is still not answered.
