### ISSUE TITLE
Getting message received event infinitly

### ISSUE THREAD

**Issue by febinpaul** [podshumok/python-smpplib#11]
Thank you for this powerful application.

I just tried this code and made bid change ie executed the thread to listen for the incoming message , when one sends  message, it executes _message_received  function . At the end I just called send_message function. The code is working but on my 1st message send and receives it again receiving my previous message and again  executes _message_received  function and send message.
This process continues till I stops the script execution.

///////////code//////////////
def _message_received(self, p):
        """Handler for received message event"""

        self.message_received_handler(pdu=p)
        dsmr = smpp.make_pdu('deliver_sm_resp', client=self)
        #, message_id=args['pdu'].sm_default_msg_id)
        dsmr.sequence = p.sequence
        self.send_pdu(dsmr)
        print "My message:"
        print p.short_message
        print "My number:"
        print p.source_addr

        sendXML = test_xmphttp.SendXMLHTTP()
        # print dir(sendXML)
        getStatus = sendXML.sendXMLPost(p.source_addr,p.short_message)

        print getStatus
        if(getStatus['status'] == 'success'):
            parts, encoding_flag, msg_type_flag = gsm.make_parts(getStatus['data'])
           
            # for part in parts:
            for part in parts:
                
                self.send_message(
                    source_addr_ton=consts.SMPP_TON_INTL,
                    # source_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
                    source_addr='55555',
                    dest_addr_ton=consts.SMPP_TON_INTL,
                    # dest_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
                    destination_addr=p.source_addr,
                    short_message=part,
                    data_coding=encoding_flag,
                    esm_class=msg_type_flag,
                    registered_delivery=True,
                )
                # print(pdu.sequence)

/////////code ends//////////
Can you please help me to get the solution.
Thank you,

**Comment by febinpaul** [comment]
replace :   registered_delivery=True,
with  :   registered_delivery=False,

**Comment by podshumok** [comment]
You shouldn't call `message_received_handler` - it will be called for you, when client reads `DELIVER_SM`
