### ISSUE TITLE
Encoding issue with Hebrew text

### ISSUE THREAD

**Issue by sgilabert** [podshumok/python-smpplib#16]
Dear,
We are getting an encoding error when we try to send messages in Hebrew. We tried using the example you provided. It works for Russian (the one you provided) but for Hebrew it raises the following exception. Is it Hebrew supported?

Thanks,
Best Regards,
Santiago

```
  File "/home/sgilabert/git/server/smpplib/client.py", line 321, in send_message
    self.send_pdu(ssm)
  File "/home/sgilabert/git/server/smpplib/client.py", line 172, in send_pdu
    generated = p.generate()
  File "/home/sgilabert/git/server/smpplib/pdu.py", line 142, in generate
    body = self.generate_params()
  File "/home/sgilabert/git/server/smpplib/command.py", line 150, in generate_params
    body += value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd4 in position 1: ordinal not in range(128)
```
HEBREW EXAMPLE THAT FAILS
```
      parts, encoding_flag, msg_type_flag = gsm.make_parts(u'ה נשמע ח')
      client = smpplib.client.Client(host, port)
      client.connect()
      client.bind_transmitter(system_id=system_id, password=pass, system_type=sys_type)
      .
      .
      .
      for part in parts:
        client.send_message(
          source_addr_ton = source_ton,
          source_addr_npi = source_npi,
          source_addr = source_addr,
          dest_addr_ton = dest_ton,
          dest_addr_npi = dest_npi,
          short_message=part,
          data_coding=encoding_flag,
          esm_class=msg_type_flag,
        )
```

RUSSIAN  EXAMPLE THAT WORKS
```
      parts, encoding_flag, msg_type_flag = gsm.make_parts(u'Привет мирח')
      client = smpplib.client.Client(host, port)
      client.connect()
      client.bind_transmitter(system_id=system_id, password=pass, system_type=sys_type)
      .
      .
      .
      for part in parts:
        client.send_message(
          source_addr_ton = source_ton,
          source_addr_npi = source_npi,
          source_addr = source_addr,
          dest_addr_ton = dest_ton,
          dest_addr_npi = dest_npi,
          short_message=part,
          data_coding=encoding_flag,
          esm_class=msg_type_flag,
        )
```

**Comment by podshumok** [comment]
Please provide full traceback from failing example and values of `parts, encoding_flag, msg_type_flag` after `gsm.make_parts` call

**Comment by sgilabert** [comment]
Hi, 

Here it is,

Thanks

WORKING EXAMPLE
original text Привет мир
parts ('\x04\x1f\x04@\x048\x042\x045\x04B\x00 \x04<\x048\x04@',)
encoding_flag 8
msg_type_flag 0

NOT WORKING EXAMPLE
original text ה נשמע ח
parts ('\x05\xd4\x00 \x05\xe0\x05\xe9\x05\xde\x05\xe2\x00 \x05\xd7',)
encoding_flag 8
msg_type_flag 0

ERROR 2015-10-03 18:12:11,576 gaia.gateway_core send_message() 27230: SMS not sent (SMPP) by Dasprojur-Messente
Traceback (most recent call last):
  File "/home/sgilabert/git/safewalk-server/gateway_core/smpp/handlers.py", line 66, in send_message
    esm_class=msg_type_flag,
  File "/home/sgilabert/git/safewalk-server/smpplib/client.py", line 321, in send_message
    self.send_pdu(ssm)
  File "/home/sgilabert/git/safewalk-server/smpplib/client.py", line 172, in send_pdu
    generated = p.generate()
  File "/home/sgilabert/git/safewalk-server/smpplib/pdu.py", line 142, in generate
    body = self.generate_params()
  File "/home/sgilabert/git/safewalk-server/smpplib/command.py", line 150, in generate_params
    body += value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd4 in position 1: ordinal not in range(128)

**Comment by podshumok** [comment]
Well, looks like `make_parts` does its job correctly.
Could you, please, provide all the params you call `smpplib.client.Client.send_message` with?

**Comment by podshumok** [comment]
Also, please check, that you don't pass `unicode` objects to this method.

**Comment by sgilabert** [comment]
Sure

I added the following prints inside the for 

print 'source_addr_ton', source_ton
print 'source_addr_npi', source_npi
print 'source_addr', source_addr
print 'dest_addr_ton', dest_ton
print 'dest_addr_npi', dest_npi
print 'short_message', part
print 'data_coding', encoding_flag
print 'esm_class', msg_type_flag

WORKING EXAMPLE
encoding_flag 8
msg_type_flag 0
source_addr_ton 5
source_addr_npi 0
source_addr Dasprojur
dest_addr_ton 1
dest_addr_npi 1
short_message @825B <8@
data_coding 8
esm_class 0

NOT WORKING EXAMPLE
source_addr_ton 5
source_addr_npi 0
source_addr Dasprojur
dest_addr_ton 1
dest_addr_npi 1
short_message � ���� 
data_coding 8
esm_class 0

Thanks

**Comment by sgilabert** [comment]
You think this is because of what is passed in short_message?

**Comment by podshumok** [comment]
Somehow these to params are missing in Not working example:
```
encoding_flag 8
msg_type_flag 0
```

Could you please add `print type(...)` statements?

**Comment by sgilabert** [comment]
Sorry, was an error on the copy paste. The values for those two params are the same on working and not working example

encoding_flag 8
msg_type_flag 0

Bellow is the print type(...) statements

        print 'source_addr_ton', source_ton, type(source_ton)
        print 'source_addr_npi', source_npi, type(source_npi)
        print 'source_addr', source_addr, type(source_addr)
        print 'dest_addr_ton', dest_ton, type(dest_ton)
        print 'dest_addr_npi', dest_npi, type(dest_npi)
        print 'short_message', part, type(part)
        print 'data_coding', encoding_flag, type(encoding_flag)
        print 'esm_class', msg_type_flag, type(msg_type_flag)

NOT WORKING EXAMPLE
source_addr_ton 5 <type 'int'>
source_addr_npi 0 <type 'int'>
source_addr Dasprojur <type 'unicode'>
dest_addr_ton 1 <type 'int'>
dest_addr_npi 1 <type 'int'>
short_message � ���� � <type 'str'>
data_coding 8 <type 'int'>
esm_class 0 <type 'int'>

Ajá! source_addr is unicode. I made an additional test, with str(source_addr) and it worked. Its strange because for the Russian example was unicode too, but it works.

WORKING EXAMPLE

encoding_flag 8
msg_type_flag 0
source_addr_ton 5 <type 'int'>
source_addr_npi 0 <type 'int'>
source_addr Dasprojur <type 'unicode'>
dest_addr_ton 1 <type 'int'>
dest_addr_npi 1 <type 'int'>
short_message @825B <8@� <type 'str'>
data_coding 8 <type 'int'>
esm_class 0 <type 'int'>

I'm closing this one. Many Thanks for your help a very quick reply
