### ISSUE TITLE
The delivery report message?

### ISSUE THREAD

**Issue by Diuzhih** [podshumok/python-smpplib#26]
How can I get the delivery report of the message?

**Comment by podshumok** [comment]
Yes.
See this files in readme:

```
client.set_message_received_handler(
    lambda pdu: sys.stdout.write('delivered {}\n'.format(pdu.receipted_message_id)))
```

**Comment by lasdolphin** [comment]
Hello, my problem is  that destination smpp server returns "NO SMSC delivery receipt requested"
[https://www.dropbox.com/s/nec2aeo5e3a801v/Screenshot%202017-07-18%2013.11.31.png?dl=0]

**Comment by podshumok** [comment]
I'm sorry, but I have no idea of what is on that picture.
How do you call `send_message` function?

**Comment by lasdolphin** [comment]
`for part in parts:
    pdu = client.send_message(
        source_addr_ton=smpplib.consts.SMPP_TON_INTL,
        #source_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
        # Make sure it is a byte string, not unicode:
	source_addr='TEST',

        dest_addr_ton=smpplib.consts.SMPP_TON_INTL,
        #dest_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
        # Make sure thease two params are byte strings, not unicode:
        destination_addr='****',
        short_message=part,

        data_coding=encoding_flag,
        esm_class=msg_type_flag,
        registered_delivery=True,
    )
    print(pdu.sequence)`

**Comment by podshumok** [comment]
`registered_delivery` is set, so it should be ok...

**Comment by boluo123456** [comment]
@podshumok I also met same issue. 
can't get delivery report even set registered_delivery=True.

**Comment by podshumok** [comment]
Do you have `set_message_received_handler` set?

**Comment by ywshzh** [comment]
@podshumok  yes，i  am set. this is my code:
`parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(u'hello world!\n'*10)

client = smpplib.client.Client(ip, port)

def sent_handler(pdu):
	print "sent: ", pdu.sequence, pdu.message_id, pdu.status
	
def received_handler)(pdu):
	print "delivered: ", pdu.receipted_message_id

client.set_message_sent_handler(sent_handler)
client.set_message_received_handler(received_handler)	

client.connect()
client.bind_transceiver(system_id=sysid, password=passwd)

for part in parts:
    pdu = client.send_message(
        source_addr_ton=smpplib.consts.SMPP_TON_INTL,
        source_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
        # Make sure it is a byte string, not unicode:
        #source_addr='SENDERPHONENUM',
        source_addr='111',

        dest_addr_ton=smpplib.consts.SMPP_TON_INTL,
        dest_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
        # Make sure thease two params are byte strings, not unicode:
        #destination_addr='PHONENUMBER',
        destination_addr='222',
        short_message=part,

        data_coding=encoding_flag,
        esm_class=msg_type_flag,
        registered_delivery=True,
    )
    print(pdu.sequence)

client.listen()`

**Comment by ywshzh** [comment]
@podshumok  yes，i am set. this is my code:

`parts, encoding_flag, msg_type_flag = smpplib.gsm.make_parts(u'hello world!\n'*10)

client = smpplib.client.Client(ip, port)

def sent_handler(pdu):
	print "sent: ", pdu.sequence, pdu.message_id, pdu.status
	
def received_handler)(pdu):
	print "delivered: ", pdu.receipted_message_id

client.set_message_sent_handler(sent_handler)
client.set_message_received_handler(received_handler)	

client.connect()
client.bind_transceiver(system_id=sysid, password=passwd)

for part in parts:
    pdu = client.send_message(
        source_addr_ton=smpplib.consts.SMPP_TON_INTL,
        source_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
        # Make sure it is a byte string, not unicode:
        #source_addr='SENDERPHONENUM',
        source_addr='111',

        dest_addr_ton=smpplib.consts.SMPP_TON_INTL,
        dest_addr_npi=smpplib.consts.SMPP_NPI_ISDN,
        # Make sure thease two params are byte strings, not unicode:
        #destination_addr='PHONENUMBER',
        destination_addr='222',
        short_message=part,

        data_coding=encoding_flag,
        esm_class=msg_type_flag,
        registered_delivery=True,
    )
    print(pdu.sequence)

client.listen()`

**Comment by boluo123456** [comment]
@podshumok Please check the issue of `'utf8' codec can't decode byte 0x96 in position 0: invalid start byte`

**Comment by boluo123456** [comment]
It is solved.

**Comment by kobbyopoku** [comment]
How do I turn delivery reports off? I don't want to receive delivery reports

**Comment by eigenein** [comment]
Just don't set `registered_delivery` @kobbyopoku
