### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by pespin** [podshumok/python-smpplib#29]
Hi, I was trying to use smpplib with python 3 today, and I noticed there were some loines of code which were not compatible with it.

I created a fork with quick fixes for that: https://github.com/pespin/python-smpplib/commits/pespin/devel
Not sure what's the best idea regarding python3 though. Is anybody willing to use it with python2? Can we drop python 2 support or we need to support both somehow?

**Comment by podshumok** [comment]
I think, that python3 users should look towards asyncio-based libraries here.

On the other hand, I think it is not big deal to support both python3 and python2 here (matter of testing basically).  We definitely can drop python2.5 support (`except .., ...`) syntax. Everything else can be covered with `six`. (`dict.iteritems() -> six.iteritems(dict)`, `six.b` for byte-strings and that's it, no other python2-only features used in library, I believe).

**Comment by pespin** [comment]
Hi, thanks for your detailed answer.
I'll provide a patch over next week to fix all python2/3 support issues.
I'll look into asyncio stuff too, never used those. For now I'm splitting the listen into a poll() function and using select() there to know whether the recv call is gonna block or not, but I want to merge some fix for that at some point too.

**Comment by podshumok** [comment]
looks like some guys have already done some porting
a841fefeceb437306ec856e21db621f28b518796
651cc15c2bfe24526f71192ddcb22ee69ab8cead
for example

**Comment by pespin** [comment]
Hi thanks for the pointers.
However, I'm a bit lost, those commits seem to be in the same repository but I cannot find in which branch are they nor I can see them using "git show" in my local copy?

**Comment by podshumok** [comment]
Those are in forks, not in main repo

**Comment by pespin** [comment]
Yes that's what I thought but the links seems to point to this same repository.
Those commits drop support for python 2 as far as I can see, I'll prepare some commits to have support for both.

**Comment by pespin** [comment]
This can be closed as patches were merged to support both python 2 and 3 by using python-six module. Thanks for merging them.

**Comment by komuw** [comment]
> I think, that python3 users should look towards asyncio-based libraries here.  

I wrote an syncio based smpp client -> https://github.com/komuw/naz 
feedback is welcome
