### ISSUE TITLE
Line Break

### ISSUE THREAD

**Issue by asadmehmood1234** [podshumok/python-smpplib#41]
I'm trying to send the message with line breaks between the lines. The message is sent over but without line breaks (new lines). I've tried "/n" , "/r" , %0A but didn't work any of these...Appreciate if you could help me with the issues.

**Comment by podshumok** [comment]
`\n` and/or `\r` should work. Please provide a piece of code you use if they don't.

**Comment by eigenein** [comment]
Hi @asadmehmood1234,

Is this still an issue for you?

**Comment by eigenein** [comment]
`\n` and `\r` are also working for me. I'm closing the issue, please re-open it if it still applies.
